src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Is_Foundation_Donation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be checked at setup for all Foundation Donation Items. This field is being used in Trigger on Renewal of membership items</description>
        <inlineHelpText>This field will be checked at setup for all Foundation Donation Items. This field is being used in Trigger on Renewal of membership items</inlineHelpText>
        <label>Is Foundation Donation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
        <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
        <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Is_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, related Sales Order Line is considered as &quot;Subscription Renewal&quot;.</description>
        <inlineHelpText>When checked, related Sales Order Line is considered as &quot;Subscription Renewal&quot;.</inlineHelpText>
        <label>Is Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</description>
        <inlineHelpText>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</inlineHelpText>
        <label>Price Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sale_Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
        <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Subscription that is being upgraded or renewed.</description>
        <inlineHelpText>Link to the Subscription that is being upgraded or renewed.</inlineHelpText>
        <label>Subscription (Upgrade/Renew)</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** The source Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated ** The source Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Sales Order Line (Source)</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Enable_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, subscribers will pay for subscriptions in installments - the frequency/amount is driven by the schedule options configuration fields. Defaults unchecked.</description>
        <inlineHelpText>When checked, subscribers will pay for subscriptions in installments - the frequency/amount is driven by the schedule options configuration fields. Defaults unchecked.</inlineHelpText>
        <label>Enable Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
        <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateSalesOrderLine.cls
public class CreateSalesOrderLine{

    public static void SalesOrderLinesForItems(list<OrderApi__Sales_Order_Line__c> listOfSalesOrderLines ){
    
    list<OrderApi__Sales_Order_Line__c> salesorderLinelist=new list<OrderApi__Sales_Order_Line__c>();
    set<Id> setIdSalesOrder=new set<Id>();
    set<Id> setIdSubscription=new set<Id>();
    set<Id> SalesOrderSetId =new set<Id>();
    set<Id> allsubscriptionId =new set<Id>();
    list<OrderApi__Item__c> ConvenienceItem=[select id,OrderApi__Price__c from OrderApi__Item__c where name='Convenience fee' And OrderApi__Is_Active__c=true];
    map<Id,Id> mapOfSubscription=new map<Id,Id>();
    Map<Id,Id> mapOfSalesOrder = new Map<Id,Id>();
    map<Id,Id> mapOfItem=new map<Id,Id>();
    set<id> setIdItem =new set<Id>();
    set<id> setId=new set<Id>();
    
    for(OrderApi__Sales_Order_Line__c salesOrderLine:listOfSalesOrderLines){
        
        mapOfSubscription.put(salesOrderLine.Id,salesOrderLine.OrderApi__Subscription__c);                    
        allsubscriptionId.add(salesOrderLine.OrderApi__Subscription__c);
        mapOfSalesOrder.put(salesOrderLine.Id,salesOrderLine.OrderApi__Sales_Order__c);
        setIdSalesOrder.add(salesOrderLine.OrderApi__Sales_Order__c);
        mapOfItem.put(salesOrderLine.Id,salesOrderLine.OrderApi__Item__c);
        setId.add(salesOrderLine.OrderApi__Item__c);
            
            }
    if(!setIdSalesOrder.isEmpty()){
    list<OrderApi__Sales_Order__c> salesOrderList = [select id,name,(select id,name,OrderApi__Item__c from OrderApi__Sales_Order_Lines__r where OrderApi__Item__r.Name = 'Convenience fee' ) from OrderApi__Sales_Order__c Where Id in:setIdSalesOrder];
   
        if(salesOrderList.size()>0){
    for(OrderApi__Sales_Order__c salesOrder:salesOrderList){
        if(salesOrder.OrderApi__Sales_Order_Lines__r.size()>0){
            SalesOrderSetId.add(salesOrder.Id); 
        }
      }
    }
  } 
    
    if(!allsubscriptionId.isEmpty()){
    list<OrderApi__Subscription__c> subscriptionlist=[select id from OrderApi__Subscription__c where OrderApi__Subscription_Plan__r.OrderApi__Enable_Schedule__c=true];
        if(subscriptionlist.size()>0){
          for(OrderApi__Subscription__c  subscription : subscriptionlist){
           setIdSubscription.add(subscription.Id);
          }
    }
  } 
   list<OrderApi__Item__c> itemfoundationList=[select id,OrderApi__Price__c from OrderApi__Item__c where Is_Foundation_Donation__c=true And OrderApi__Is_Active__c=true ];
    if(!setId.isEmpty()) {  
      
     if(itemfoundationList.size()>0){
    for(OrderApi__Item__c item : itemfoundationList){
        
        setIdItem.add(item.Id);
      }
     }
    }
    for(OrderApi__Sales_Order_Line__c salesOrderLine:listOfSalesOrderLines){
        
        if(salesOrderLine.OrderApi__Is_Renewal__c==true && salesOrderLine.OrderApi__Subscription__c!=null && setIdSubscription.contains(mapOfSubscription.get(salesOrderLine.Id)) && !SalesOrderSetId.contains(mapOfSalesOrder.get(salesOrderLine.Id)) ){
            if(ConvenienceItem.size()>0){
            OrderApi__Sales_Order_Line__c salesOrderLineConvenienceItem=new OrderApi__Sales_Order_Line__c(); 
            salesOrderLineConvenienceItem.OrderApi__Item__c= ConvenienceItem[0].id;
            salesOrderLineConvenienceItem.OrderApi__Sale_Price__c=ConvenienceItem[0].OrderApi__Price__c;
            salesOrderLineConvenienceItem.OrderApi__Sales_Order__c=salesOrderLine.OrderApi__Sales_Order__c;
            salesorderLinelist.add(salesOrderLineConvenienceItem);
            }
        }
        if(setIdItem.contains(mapOfItem.get(salesOrderLine.Id))){
           OrderApi__Sales_Order_Line__c salesOrderLineFoundationItem=new OrderApi__Sales_Order_Line__c();
           salesOrderLineFoundationItem.OrderApi__Item__c=itemfoundationList[0].Id;
           salesOrderLineFoundationItem.OrderApi__Sale_Price__c=itemfoundationList[0].OrderApi__Price__c;
           salesOrderLineFoundationItem.OrderApi__Price_Override__c =true;
           salesOrderLineFoundationItem.OrderApi__Sales_Order__c=salesOrderLine.OrderApi__Sales_Order__c;
           salesOrderLinelist.add(salesOrderLineFoundationItem);
        }
        
         
    }
    if(salesorderLinelist.size()>0){
    insert salesorderLinelist;
    }
}


    
    
    
}