src/objects/OrderApi__Payment_Gateway__c.object
<CustomObject>
    <description>Payment gateways store configuration data for all connected Fonteva payment gateways in your organization.</description>
    <fields>
        <fullName>OrderApi__Is_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The gateway is enabled for payment processing.</description>
        <inlineHelpText>The gateway is enabled for payment processing.</inlineHelpText>
        <label>Is Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Test__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The gateway is a test gateway and not to be used for production environments.</description>
        <inlineHelpText>The gateway is a test gateway and not to be used for production environments.</inlineHelpText>
        <label>Is Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Token__c</fullName>
        <description>**System Calculated/Override** The token used by the business group to process credit card and e-checks (not supported for all customers, check with your administrator if you have any questions).</description>
        <inlineHelpText>**System Calculated/Override** The token used by the business group to process credit card and e-checks (not supported for all customers, check with your administrator if you have any questions).</inlineHelpText>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Payment_Method__c.object
<CustomObject>
    <description>Credit Card and E-Check tokens stored for accounts and contacts.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the Billing Contact for the Payment Method.</description>
        <inlineHelpText>**System Calculated/Override** Link to the Billing Contact for the Payment Method.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Payment Method ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Fon_CustomPaymentMethodCtrl.cls
public without sharing class Fon_CustomPaymentMethodCtrl{

    @AuraEnabled
    public static String getContactInfo() {
        
        try {
            user u = [SELECT ContactId,Id FROM User where id = : userinfo.getuserid()];
            if(u !=null){
                return u.contactid;
            }
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
        return null; 
    }
    
    @AuraEnabled
    public static String getTokenInfo() {
        
        try {
            if([SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox == true){
                OrderApi__Payment_Gateway__c pg = [SELECT Id, OrderApi__Token__c FROM OrderApi__Payment_Gateway__c WHERE OrderApi__Is_Test__c = True limit 1];
                if(pg !=null){
                    return pg.OrderApi__Token__c ;
                }
            } else{
                OrderApi__Payment_Gateway__c pg = [SELECT Id, OrderApi__Token__c FROM OrderApi__Payment_Gateway__c WHERE OrderApi__Is_Test__c = False AND OrderApi__Is_Enabled__c = true limit 1];
                if(pg !=null){
                    return pg.OrderApi__Token__c ;
                }
            }
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
        return null; 
    }
    
    @AuraEnabled
    public static String getPaymentMethod() {
        
        try {
            user u = [SELECT ContactId,Id FROM User where id = : userinfo.getuserid()];
            if(u !=null){
                OrderApi__Payment_Method__c pm = [SELECT Id FROM OrderApi__Payment_Method__c WHERE OrderApi__Contact__c =: u.contactid ORDER BY CreatedDate DESC LIMIT 1];
                if(pm !=null){
                    return pm.id;
                }
            }
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
        return null; 
    }
}