src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Is_Foundation_Donation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be checked at setup for all Foundation Donation Items. This field is being used in Trigger on Renewal of membership items</description>
        <inlineHelpText>This field will be checked at setup for all Foundation Donation Items. This field is being used in Trigger on Renewal of membership items</inlineHelpText>
        <label>Is Foundation Donation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Business_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
        <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
        <label>Business Group</label>
        <referenceTo>OrderApi__Business_Group__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Price_Rule__c.object
<CustomObject>
    <description>Flexible price rules allow you to configure custom price scenarios for items based on a variety of different rules.</description>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The item the price rule record is assigning a price for.</description>
        <inlineHelpText>The item the price rule record is assigning a price for.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Pricing Rules</relationshipLabel>
        <relationshipName>Price_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, related Sales Order Line is considered as &quot;Subscription Renewal&quot;.</description>
        <inlineHelpText>When checked, related Sales Order Line is considered as &quot;Subscription Renewal&quot;.</inlineHelpText>
        <label>Is Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__List_Price__c</fullName>
        <description>**System Calculated** The standard price for the item selected on the sales order line.</description>
        <formula>OrderApi__Item__r.OrderApi__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** The standard price for the item selected on the sales order line.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</description>
        <inlineHelpText>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</inlineHelpText>
        <label>Price Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Subscription that is being upgraded or renewed.</description>
        <inlineHelpText>Link to the Subscription that is being upgraded or renewed.</inlineHelpText>
        <label>Subscription (Upgrade/Renew)</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Enable_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, subscribers will pay for subscriptions in installments - the frequency/amount is driven by the schedule options configuration fields. Defaults unchecked.</description>
        <inlineHelpText>When checked, subscribers will pay for subscriptions in installments - the frequency/amount is driven by the schedule options configuration fields. Defaults unchecked.</inlineHelpText>
        <label>Enable Schedule</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesOrderLineItemMangerBatch.cls
global class Fon_SalesOrderLineItemManagerBatch implements Database.Batchable<sObject> {
    private final String strConveniencefee = 'Convenience fee';
    /**
        @Author: RSystem
        @Description: To process the soli records where creation date on SOLI is today.
    */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Collect the batches of records
        return Database.getQueryLocator('SELECT Id,Name,OrderApi__Item__c,OrderApi__Item__r.Is_Foundation_Donation__c,OrderApi__List_Price__c,OrderApi__Price_Override__c,'+
                                            'OrderApi__Is_Renewal__c,OrderApi__Subscription__c,OrderApi__Subscription__r.OrderApi__Subscription_Plan__c,'+
                                                'OrderApi__Subscription__r.OrderApi__Subscription_Plan__r.OrderApi__Enable_Schedule__c,CreatedDate,'+
                                                    'OrderApi__Account__c,OrderApi__Contact__c,OrderApi__Business_Group__c,OrderApi__Price_Rule__c,'+
                                                        'OrderApi__Sale_Price__c,OrderApi__Sales_Order__c FROM OrderApi__Sales_Order_Line__c WHERE CreatedDate = TODAY');
    }
    global void execute(Database.BatchableContext BC, List<OrderApi__Sales_Order_Line__c> lstSOLI) {
        OrderApi__Item__c objConvenienceFeeItem = fetchConvenienceFeeItem();
        List<OrderApi__Sales_Order_Line__c> lstNewSOLI = new List<OrderApi__Sales_Order_Line__c>();
        Set<Id> setSalesOrderId = new Set<Id>();
        for(OrderApi__Sales_Order_Line__c eachSOLIRecord : lstSOLI){
            setSalesOrderId.add(eachSOLIRecord.OrderApi__Sales_Order__c);
        }
        Set<Id> setConvenienceSalesOrderId = fetchConvenienceFeeSalesOrder(setSalesOrderId);
        setSalesOrderId = new Set<Id>();
        for(OrderApi__Sales_Order_Line__c eachSOLI : lstSOLI){
            if(eachSOLI.OrderApi__Is_Renewal__c && !String.isEmpty(eachSOLI.OrderApi__Subscription__c) && 
                !String.isEmpty(eachSOLI.OrderApi__Subscription__r.OrderApi__Subscription_Plan__c) && 
                    eachSOLI.OrderApi__Subscription__r.OrderApi__Subscription_Plan__r.OrderApi__Enable_Schedule__c && objConvenienceFeeItem != null && 
                        !setConvenienceSalesOrderId.contains(eachSOLI.OrderApi__Sales_Order__c)){
                OrderApi__Sales_Order_Line__c InstanceSOLI = fetchSOLIInstance(eachSOLI);
                InstanceSOLI.OrderApi__Item__c = objConvenienceFeeItem.Id;
                lstNewSOLI.add(InstanceSOLI);
                setSalesOrderId.add(eachSOLI.OrderApi__Sales_Order__c);
            }
            if(eachSOLI.OrderApi__Item__r.Is_Foundation_Donation__c){
                OrderApi__Sales_Order_Line__c InstanceSOLI = fetchSOLIInstance(eachSOLI);
                InstanceSOLI.OrderApi__Price_Override__c = true;
                InstanceSOLI.OrderApi__Sale_Price__c = eachSOLI.OrderApi__Sale_Price__c;
                lstNewSOLI.add(InstanceSOLI);
                setSalesOrderId.add(eachSOLI.OrderApi__Sales_Order__c);
            }
        }
        // Inserting List of new OrderApi__Sales_Order_Line__c
        if(!lstNewSOLI.isEmpty()){
            insert lstNewSOLI;
        }
        if(!setSalesOrderId.isEmpty()){
            List<OrderApi__Sales_Order__c> lstSalesOrder = new List<OrderApi__Sales_Order__c>();
            for(Id eachSOId : setSalesOrderId){
                lstSalesOrder.add(new OrderApi__Sales_Order__c(Id = eachSOId,Fon_Added_SOLI__c = true));
            }
            update lstSalesOrder;
        }
    }
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
    /**
        @Description: Initializing new instance of SOLI based on param(soli).
        @param: Object of OrderApi__Sales_Order_Line__c objOldSOLI as param.
        @return: New instance of OrderApi__Sales_Order_Line__c
    */
    public OrderApi__Sales_Order_Line__c fetchSOLIInstance(OrderApi__Sales_Order_Line__c objOldSOLI){
        OrderApi__Sales_Order_Line__c objSOLI = new OrderApi__Sales_Order_Line__c(OrderApi__Sales_Order__c = objOldSOLI.OrderApi__Sales_Order__c,OrderApi__Item__c = objOldSOLI.OrderApi__Item__c,
            OrderApi__Account__c = objOldSOLI.OrderApi__Account__c,OrderApi__Contact__c = objOldSOLI.OrderApi__Contact__c,OrderApi__Business_Group__c = objOldSOLI.OrderApi__Business_Group__c,
            OrderApi__Price_Rule__c = objOldSOLI.OrderApi__Price_Rule__c);
        return objSOLI;
    }
    /**
        @Description: Fetch Convenience fee Item.
        @return: New instance of OrderApi__Sales_Order_Line__c
    */
    public OrderApi__Item__c fetchConvenienceFeeItem(){
        List<OrderApi__Item__c> lstItems = [SELECT Id,OrderApi__Price__c FROM OrderApi__Item__c WHERE Name =: strConveniencefee];
        if(!lstItems.isEmpty()){
            return lstItems[0];
        }
        return null;
    }
    /**
        @Description: To fetch set of sales order record ids that have soli linked with Convenience fee Item.
        @param: Collection of sales order id Set<Id> setSalesOrderId.
        @return: sales order id's set that have soli linked with Convenience fee Item.
    */
    public Set<Id> fetchConvenienceFeeSalesOrder(Set<Id> setSalesOrderId){
        Set<Id> setConvenienceSalesOrderId = new Set<Id>();
        for(OrderApi__Sales_Order__c objSO : [SELECT Id,(SELECT Id FROM OrderApi__Sales_Order_Lines__r WHERE OrderApi__Item__r.Name =: strConveniencefee) 
                                                FROM OrderApi__Sales_Order__c WHERE Id IN :setSalesOrderId]){
            if(objSO.OrderApi__Sales_Order_Lines__r != null && !objSO.OrderApi__Sales_Order_Lines__r.isEmpty()){
                setConvenienceSalesOrderId.add(objSO.Id);
            }
        }
        return setConvenienceSalesOrderId;
    }
}